Repository 2E2I/mamomo-client, pull requests merged in 2022-04, with the labels that each got.

#85 🐛 태그페이지 새로고침 버그 수정 #84
  package.json
  src/components/searchPageComponents/CategoryTag.js
  src/components/tagPageComponents/TagPageDonationList.js
  src/components/tagPageComponents/TagTitle.js
  src/pages/TagPage/TagPage.js
  src/store/CategoryPageStore.js
  src/store/SearchPageStore.js
  src/utils/persist.js
  yarn.lock
Labels: bug

#91 🐛 메인페이지 기부리스트 버그 수정 #90
  src/components/CardList.js
  src/components/CardList_old.js
  src/components/mainPageComponents/MainPageDonationList.js
  src/components/mainPageComponents/MainPageDonationList_old.js
  src/pages/MainPage/MainPage.js
Labels: bug

#95 ✨ 카테고리 페이지 정렬기능 추가 #94
  src/components/Categories.js
  src/components/DonationListByCategorie.js
  src/components/SortBox.js
  src/store/CategoryPageStore.js
Labels: enhancement

#100 ✨ 카테고리 태그 페이지 페이징 처리 #88
  src/components/tagPageComponents/TagPageDonationList.js
  src/components/tagPageComponents/TagTitle.js
  src/pages/TagPage/TagPage.js
Labels: enhancement, react, page

#102 ✨ 로그인페이지 세팅 #101
  package-lock.json
  src/App.js
  src/pages/SignInPage/SignInPage.js
  src/pages/SignInPage/index.js
  yarn.lock
Labels: react, setting, page

#109 ✨ 로그인페이지 컴포넌트 생성 #103
  src/components/signInPageComponents/FindingID.js
  src/components/signInPageComponents/FindingPassword.js
  src/components/signInPageComponents/ID.js
  src/components/signInPageComponents/KeepingSignInButton.js
  src/components/signInPageComponents/MainTitle.js
  src/components/signInPageComponents/Password.js
  src/components/signInPageComponents/SignInButton.js
  src/components/signInPageComponents/SignUpButton.js
  src/pages/SignInPage/SignInPage.js
Labels: react, component

#113 ✨ 로그인페이지 설계 #112
  src/components/TopAppBar.js
  src/components/signInPageComponents/FindingPassword.js
  src/components/signInPageComponents/SignIn.js
  src/components/signInPageComponents/SignUp.js
Labels: react, component

#116 ✨ 회원가입페이지 세팅 #114
  src/App.js
  src/components/signInPageComponents/SignUp.js
  src/pages/SignUpPage/SignUpPage.js
  src/pages/SignUpPage/index.js
Labels: react, setting

#117 ✨ 회원가입페이지 컴포넌트 생성 #115
  src/components/signUpPageComponents/Birth.js
  src/components/signUpPageComponents/CheckingPassword.js
  src/components/signUpPageComponents/Email.js
  src/components/signUpPageComponents/NickName.js
  src/components/signUpPageComponents/Password.js
  src/components/signUpPageComponents/PreferredDonationField.js
  src/components/signUpPageComponents/Sex.js
Labels: react, setting, component

#122 💄 로그인페이지 컴포넌트 디자인 수정 #121
  src/components/signInPageComponents/Email.js
  src/components/signInPageComponents/FindingPassword.js
  src/components/signInPageComponents/KeepingSignIn.js
  src/components/signInPageComponents/Password.js
  src/components/signInPageComponents/SignIn.js
  src/components/signInPageComponents/SignUp.js
Labels: react, component, design

#132 🐛 Priview.js import오류 수정 #131
  src/components/bannerPageComponents/Preview.js
Labels: bug

#133 ✨ 로그인페이지 설계 #112
  src/components/signInPageComponents/Email.js
  src/components/signInPageComponents/KeepingSignIn.js
  src/components/signInPageComponents/Password.js
  src/components/signInPageComponents/SignIn.js
  src/components/signUpPageComponents/Birth.js
  src/components/signUpPageComponents/Email.js
  src/components/signUpPageComponents/FavTopics.js
  src/components/signUpPageComponents/NickName.js
  src/components/signUpPageComponents/Password.js
  src/components/signUpPageComponents/Sex.js
  src/components/signUpPageComponents/SignUp.js
  src/store/SignInPageStore.js
  src/store/SignUpPageStore.js
Labels: react, component, page

#139 ✨ 배너페이지 기능 구현 #138
  package.json
  src/components/DonationCard.js
  src/components/SortBox.js
  src/components/bannerPageComponents/BannerDesign.js
  src/components/bannerPageComponents/EditForm.js
  src/components/bannerPageComponents/Preview.js
  src/pages/SearchingPage/SearchingPage.js
  src/store/BannerPageStore.js
  yarn.lock
Labels: page

#141 ✨ 회원가입페이지 설계 #120
  src/components/MainTitle.js
  src/components/signUpPageComponents/CheckingPassword.js
  src/components/signUpPageComponents/Email.js
  src/components/signUpPageComponents/Nickname.js
  src/components/signUpPageComponents/SignUp.js
Labels: react, component

#146 ✨ 로그인 처리 issue/144
  src/index.js
Labels: react

#150 ✨ 로그인 상태 TopAppBar 설계
  src/App.js
  src/components/TopAppBar.js
  src/components/authenticationFunc.js
  src/components/signInPageComponents/SignIn.js
  src/store/SignInPageStore.js
Labels: react, component

#152 💄 배너리스트 페이지 디자인 #151
  src/App.js
  src/assets/images/1.PNG
  src/assets/images/2.PNG
  src/assets/images/3.PNG
  src/components/BannerListPage/BannerListPageBanner.js
  src/components/BannerListPage/MasonryImageList.js
  src/components/TopAppBar.js
  src/pages/BannerListPage/BannerListPage.js
Labels: design
