Repository 2E2I/mamomo-client, pull requests merged in 2022-06, with the labels that each got.

#248 💄 앱바를 포함한 페이지 디자인 수정 #247
  src/pages/BannerListPage/BannerListPage.js
  src/pages/CategoryPage/CategoryPage.js
  src/pages/MakeBannerPage/MakeBannerPage.js
  src/pages/MyPage/LikePage.js
  src/pages/MyPage/ManagingPage.js
  src/pages/MyPage/MyBannerPage.js
  src/pages/MyPage/MyPage.js
  src/pages/SearchPage/SearchPage.js
  src/pages/SearchingPage/SearchingPage.js
  src/pages/TagPage/TagPage.js
  src/pages/textMiningPage/TextMiningPage.js
Labels: design

#254 📝 README 작성
  README.md
  src/assets/images/readMe/기부모아.png
  src/assets/images/readMe/기부추천.png
  src/assets/images/readMe/메인화면.png
  src/assets/images/readMe/배너제작.png
  src/assets/images/readMe/시스템구조도.png
Labels: documentation

#255 📝 README 작성 #253
  README.md
Labels: documentation

#257 ⚡️ 회원가입 성공 라우팅 추가 #256
  src/components/signUpPageComponents/SignUp.js
Labels: enhancement
