Repository 2E2I/mamomo-client, pull requests merged in 2022-03, with the labels that each got.

#2 React 환경설정
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/dummy.txt
  src/components/dummy.txt
  src/index.js
  src/pages/dummy.txt
  store/dummy.txt
  styles/dummy.txt
  yarn.lock
Labels: react, setting

#9 ✨ 메인페이지 생성 및 라우팅 설정 #3
  src/App.js
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/index.js
Labels: react

#24 검색창 디자인
  package.json
  src/components/AngledSearchBar.js
  src/components/RoundSearchBar.js
  yarn.lock
Labels: component, design

#25 검색페이지 생성 및 라우팅 설정 #10
  package-lock.json
  src/App.js
  src/pages/SearchPage/SearchPage.js
  src/pages/SearchPage/index.js
Labels: react

#44 🎨 공용 컴포넌트와 메인페이지 컴포넌트 구분 #42
  src/components/Categories.js
  src/components/DonationCard.js
  src/components/dummy.txt
  src/components/mainPageComponents/Carousel.js
  src/components/mainPageComponents/MainPageDonationList.js
  src/pages/DesignTestPage/DesignTestPage.js
Labels: setting

#54 :lipstick: 태그 디자인 수정 #51
  src/components/searchPageComponents/SearchPageTagTitle.js
  src/components/searchPageComponents/SearchPageTags.js
Labels: react, design

#56 ✨ 기부리스트 모달 기능 테스트 설계 #55
  src/assets/images/icon-facebook.png
  src/assets/images/icon-kakao.png
  src/assets/images/icon-twitter.png
  src/components/DonationCard.js
  src/components/DonationModal.js
Labels: component

#58 🎨 앱바 코드 및 디자인 개선 #57
  src/assets/fonts/fonts.css
  src/components/TopAppBar.js
Labels: design

#61 ✨모든 카테고리 설계 #22
  src/components/OldSearchPageTagTitle.js
  src/components/OldSearchPageTags.js
  src/components/searchPageComponents/CategoryTag.js
  src/components/searchPageComponents/SearchPageTagTitle.js
  src/components/searchPageComponents/Tag.js
  src/components/searchPageComponents/TagList.js
  src/pages/SearchPage/SearchPage.js
Labels: react, component

#65 ✨ 인기태그 설계 #21
  src/components/searchPageComponents/RecomendationTagTitle.js
  src/components/searchPageComponents/Top10Tag.js
  src/components/searchPageComponents/Top10TagTitle.js
  src/pages/SearchPage/SearchPage.js
Labels: react, component

#75 ✨ 카테고리페이지 기부리스트 설계 #74
  src/components/DonationListByCategorie.js
Labels: component

#81 ✨ 태그 페이지 디자인, 카테고리 검색 설계 (#80, #66)
  src/App.js
  src/components/searchPageComponents/CategoryTag.js
  src/components/tagPageComponents/TagPageDonationList.js
  src/components/tagPageComponents/TagTitle.js
  src/pages/TagPage/TagPage.js
  src/store/SearchPageStore.js
Labels: react, component, page, design
