Repository 2E2I/mamomo-client, pull requests merged in 2022-05, with the labels that each got.

#154 🐛 새로고침시 로그아웃되는 버그 수정 #153
  src/App.js
  src/components/TopAppBar.js
  src/store/SignInPageStore.js
Labels: design

#157 🐛 회원가입 버그 수정 #156
  src/components/signUpPageComponents/Birth.js
Labels: bug

#158 ✨ 회원가입 유효성 검사 추가 #155
  src/components/SplitedLine.js
  src/components/signInPageComponents/Email.js
  src/components/signInPageComponents/Password.js
  src/components/signUpPageComponents/CheckingPassword.js
  src/components/signUpPageComponents/Email.js
  src/components/signUpPageComponents/FavTopics.js
  src/components/signUpPageComponents/Nickname.js
  src/components/signUpPageComponents/Password.js
  src/components/signUpPageComponents/Sex.js
  src/components/signUpPageComponents/SignUp.js
  src/store/SignUpPageStore.js
Labels: enhancement, component

#159 ✨ 회원가입 유효성 검사 추가 #155
  src/components/signInPageComponents/Email.js
  src/components/signUpPageComponents/Birth.js
Labels: enhancement, component

#161 ✨ 좋아요 기능 구현 #160
  src/App.js
  src/components/DonationCard.js
  src/components/DonationListByCategory.js
  src/components/TopAppBar.js
  src/components/mainPageComponents/MainPageDonationList.js
  src/store/SignInPageStore.js
Labels: enhancement

#164 💄마이페이지 디자인 #140
  src/App.js
  src/assets/images/profileImg.png
  src/components/TopAppBar.js
  src/components/myPageComponents/Title.js
  src/components/myPageComponents/UserTab.js
  src/pages/MainPage/MainPage.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/index.js
  src/store/MyPageStore.js
Labels: page, design

#165 ✨ 마이페이지 라우팅
  src/App.js
Labels: page

#167 🐛 배너 제작 페이지 버그수정 #166
  src/components/bannerPageComponents/EditForm.js
  src/store/BannerPageStore.js
Labels: bug

#171 ✨ 좋아요한 기부 페이지 설계 #170
  src/components/myPageComponents/Title.js
  src/components/myPageComponents/likePageComponents/LikePageDonationList.js
  src/pages/MyPage/LikePage.js
Labels: react, component, page

#174 🐛 로그인 · 로그아웃 버그 수정 #173
  src/pages/MainPage/MainPage.js
  src/pages/SignInPage/SignInPage.js
Labels: bug

#176 🐛 UserTab 버그 수정 #175
  src/pages/MyPage/LikePage.js
  src/pages/MyPage/ManagingPage.js
  src/pages/MyPage/MyBannerPage.js
Labels: bug

#178 ✨ 프로필 데이터 저장 로직 변경 #177
  src/components/TopAppBar.js
  src/components/myPageComponents/UserTab.js
  src/components/myPageComponents/managingPageComponents/Birth.js
  src/components/myPageComponents/managingPageComponents/FavTopics.js
  src/components/myPageComponents/managingPageComponents/Nickname.js
  src/components/myPageComponents/managingPageComponents/Sex.js
  src/components/signInPageComponents/SignIn.js
  src/store/UserProfileStore.js
Labels: enhancement, react

#182 🐛 좋아요 취소 버그 수정 #181
  src/components/DonationCard.js
Labels: bug

#187 ✨ 프로필 수정 버튼 설계 #172
  src/components/myPageComponents/managingPageComponents/Birth.js
  src/components/myPageComponents/managingPageComponents/CancelButton.js
  src/components/myPageComponents/managingPageComponents/FavTopics.js
  src/components/myPageComponents/managingPageComponents/Nickname.js
  src/components/myPageComponents/managingPageComponents/SaveButton.js
  src/components/myPageComponents/managingPageComponents/Sex.js
  src/store/ModifyProfileStore.js
Labels: bug, react, component

#189 🐛 배너 제작 페이지 이미지 업로드 버그 수정 #188
  src/components/bannerPageComponents/EditForm.js
Labels: bug

#190 ✨ 프로필 관심 기부 분야 수정 설계 #172
  src/components/myPageComponents/managingPageComponents/SaveButton.js
Labels: react, component

#192 💄 기부 목록 상단에 사이트 타입 표시 #191
  src/assets/images/cherry.PNG
  src/assets/images/goat_logo.png
  src/assets/images/hb2.PNG
  src/assets/images/zzo.jpg
  src/components/DonationCard.js
Labels: design

#193 ✨ 프로필 이미지 수정 설계 #172
  src/components/TopAppBar.js
  src/components/myPageComponents/UserTab.js
  src/components/myPageComponents/managingPageComponents/ProfileImg.js
  src/components/myPageComponents/managingPageComponents/SaveButton.js
  src/components/signInPageComponents/SignIn.js
  src/store/ModifyProfileStore.js
  src/store/UserProfileStore.js
Labels: react, component

#196 🐛 기부글에서 배너제작 이동시 경로변경 방법 변경 #195
  src/components/DonationModal.js
Labels: bug

#197 ✨💄 텍스트마이닝 페이지 디자인 및 설계 #194
  src/App.js
  src/components/TopAppBar.js
  src/components/textMiningPageComponents/SaveButton.js
  src/components/textMiningPageComponents/TextMiningField.js
  src/components/textMiningPageComponents/TextMiningPageBanner.js
  src/components/textMiningPageComponents/TextMiningPageDonationList.js
  src/pages/textMiningPage/TextMiningPage.js
  src/pages/textMiningPage/index.js
  src/store/TextMiningPageStore.js
Labels: component, page, design

#198 ⚡️ 프로필 수정 버튼 설계 #172
  src/components/myPageComponents/managingPageComponents/ProfileImg.js
  src/components/myPageComponents/managingPageComponents/SaveButton.js
  src/store/UserProfileStore.js
Labels: enhancement, component

#203 ✨ 프로필 이미지 서버 저장 구현 #172
  src/components/myPageComponents/managingPageComponents/ProfileImg.js
  src/components/myPageComponents/managingPageComponents/SaveButton.js
  src/components/signInPageComponents/SignIn.js
  src/store/ModifyProfileStore.js
Labels: enhancement, component

#204 ✨ 텍스트마이닝페이지 로딩바 추가 #199
  src/components/textMiningPageComponents/SaveButton.js
Labels: enhancement, component

#206 ✨ 모든 태그 설계 #205
  src/components/searchPageComponents/AllTag.js
  src/components/searchPageComponents/AllTagTitle.js
  src/components/searchPageComponents/CategoryTag.js
  src/components/searchPageComponents/Top10Tag.js
  src/components/tagPageComponents/AllTagDonationList.js
  src/pages/SearchPage/SearchPage.js
  src/pages/TagPage/TagPage.js
Labels: react, component, design

#212 ✨ 배너 저장 폼데이터 수정 및 배너리스트 페이지 get메소드 구현 #211
  src/components/BannerListPage/MasonryImageList.js
  src/components/bannerPageComponents/Preview.js
Labels: component

#216 🐛 추천 기능 debounce설정 #215
  src/components/DonationCard.js
Labels: bug

#218 ✨ 내가 만든 배너 설계 #217
  src/components/BannerListPage/MasonryImageList.js
  src/components/myPageComponents/myBannerPageComponents/MyBannerList.js
  src/pages/MyPage/LikePage.js
  src/pages/MyPage/MyBannerPage.js
Labels: react, component

#220 🐛 프로필 관리 페이지 버그 수정 #219
  src/components/myPageComponents/managingPageComponents/Birth.js
  src/components/myPageComponents/managingPageComponents/SaveButton.js
Labels: bug

#222 ⚡️ 로그인 엔터키 기능 추가 #221
  src/components/signInPageComponents/Email.js
  src/components/signInPageComponents/Password.js
  src/components/signInPageComponents/SignUp.js
  src/pages/SignInPage/SignInPage.js
Labels: enhancement

#228 ⚡️ 모든 태그 설계 수정 #227
  src/components/searchPageComponents/AllTag.js
  src/components/searchPageComponents/AllTagTitle.js
  src/components/searchPageComponents/CategoryTagTitle.js
  src/components/searchPageComponents/RecomendationTagTitle.js
  src/components/searchPageComponents/Top10Tag.js
  src/components/searchPageComponents/Top10TagTitle.js
  src/pages/SearchPage/SearchPage.js
Labels: enhancement, component, design

#229 ✨ 검색 설계 수정 #123
  src/components/RoundSearchBar.js
  src/components/searchingPageComponents/SearchingPageDonationList.js
  src/components/searchingPageComponents/SearchingPageSearchBar.js
  src/components/tagPageComponents/AllTagDonationList.js
  src/components/tagPageComponents/CategoryTagDonationList.js
  src/pages/SearchPage/SearchPage.js
  src/pages/SearchingPage/SearchingPage.js
  src/pages/TagPage/TagPage.js
  src/store/SearchPageStore.js
Labels: enhancement, component, design

#231 💄 텍스트마이닝페이지 기부글 정렬 수정 #230
  src/components/textMiningPageComponents/SaveButton.js
Labels: component, design

#233 ⚡️ 🐛 텍스트마이닝페이지 sortIndex 초기화 #232
  src/pages/textMiningPage/TextMiningPage.js
Labels: bug, enhancement

#235 💄 앱바 타이틀 로고 수정 #234
  src/components/TopAppBar.js
Labels: design

#238 🎨 배너 편집 기능 수정 #237
  src/components/bannerPageComponents/Preview.js
  src/components/myPageComponents/myBannerPageComponents/MyBannerList.js
Labels: enhancement

#240 ⚡️ 🐛 텍스트마이닝페이지 sortIndex 초기화 #232
  src/components/textMiningPageComponents/SaveButton.js
  src/pages/textMiningPage/TextMiningPage.js
Labels: bug, enhancement

#242 💄 메인페이지 디자인 수정 (테스트) #236
  src/assets/images/main05.png
  src/assets/images/main98.png
  src/assets/images/main99.png
  src/components/TopAppBar.js
  src/components/mainPageComponents/MainTestComponent.js
  src/pages/MainPage/MainPage.js
Labels: design
